version: "3.3"

services:
  db:
    image: mysql:8.0.23
    restart: always
    expose:
      - 3333
    ports:
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: diplom
